/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables;


import crawler.jra.dao.Ihq2xbiptmm0mjtp;
import crawler.jra.dao.Indexes;
import crawler.jra.dao.Keys;
import crawler.jra.dao.tables.records.RaceOddsUmrnRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceOddsUmrn extends TableImpl<RaceOddsUmrnRecord> {

    private static final long serialVersionUID = -383759517;

    /**
     * The reference instance of <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN</code>
     */
    public static final RaceOddsUmrn RACE_ODDS_UMRN = new RaceOddsUmrn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceOddsUmrnRecord> getRecordType() {
        return RaceOddsUmrnRecord.class;
    }

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.KAISAI_CD</code>.
     */
    public final TableField<RaceOddsUmrnRecord, String> KAISAI_CD = createField("KAISAI_CD", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.RACE_NO</code>.
     */
    public final TableField<RaceOddsUmrnRecord, UByte> RACE_NO = createField("RACE_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.ODDS_TIME_NO</code>.
     */
    public final TableField<RaceOddsUmrnRecord, UByte> ODDS_TIME_NO = createField("ODDS_TIME_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.UMA_NO_1</code>.
     */
    public final TableField<RaceOddsUmrnRecord, UByte> UMA_NO_1 = createField("UMA_NO_1", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.UMA_NO_2</code>.
     */
    public final TableField<RaceOddsUmrnRecord, UByte> UMA_NO_2 = createField("UMA_NO_2", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.NINKI_NO</code>.
     */
    public final TableField<RaceOddsUmrnRecord, UByte> NINKI_NO = createField("NINKI_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.SORT_NO</code>.
     */
    public final TableField<RaceOddsUmrnRecord, UByte> SORT_NO = createField("SORT_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.UMRN_ODDS</code>.
     */
    public final TableField<RaceOddsUmrnRecord, BigDecimal> UMRN_ODDS = createField("UMRN_ODDS", org.jooq.impl.SQLDataType.DECIMAL(6, 1), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.DIFF_RT</code>.
     */
    public final TableField<RaceOddsUmrnRecord, BigDecimal> DIFF_RT = createField("DIFF_RT", org.jooq.impl.SQLDataType.DECIMAL(4, 2), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.INSERT_DTTM</code>.
     */
    public final TableField<RaceOddsUmrnRecord, Timestamp> INSERT_DTTM = createField("INSERT_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN.UPDATE_DTTM</code>.
     */
    public final TableField<RaceOddsUmrnRecord, Timestamp> UPDATE_DTTM = createField("UPDATE_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN</code> table reference
     */
    public RaceOddsUmrn() {
        this(DSL.name("RACE_ODDS_UMRN"), null);
    }

    /**
     * Create an aliased <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN</code> table reference
     */
    public RaceOddsUmrn(String alias) {
        this(DSL.name(alias), RACE_ODDS_UMRN);
    }

    /**
     * Create an aliased <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN</code> table reference
     */
    public RaceOddsUmrn(Name alias) {
        this(alias, RACE_ODDS_UMRN);
    }

    private RaceOddsUmrn(Name alias, Table<RaceOddsUmrnRecord> aliased) {
        this(alias, aliased, null);
    }

    private RaceOddsUmrn(Name alias, Table<RaceOddsUmrnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RaceOddsUmrn(Table<O> child, ForeignKey<O, RaceOddsUmrnRecord> key) {
        super(child, key, RACE_ODDS_UMRN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ihq2xbiptmm0mjtp.IHQ2XBIPTMM0MJTP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RACE_ODDS_UMRN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RaceOddsUmrnRecord> getPrimaryKey() {
        return Keys.KEY_RACE_ODDS_UMRN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RaceOddsUmrnRecord>> getKeys() {
        return Arrays.<UniqueKey<RaceOddsUmrnRecord>>asList(Keys.KEY_RACE_ODDS_UMRN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RaceOddsUmrnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RaceOddsUmrnRecord, ?>>asList(Keys.RACE_ODDS_UMRN_IBFK_1);
    }

    public RaceOdds raceOdds() {
        return new RaceOdds(this, Keys.RACE_ODDS_UMRN_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsUmrn as(String alias) {
        return new RaceOddsUmrn(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsUmrn as(Name alias) {
        return new RaceOddsUmrn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceOddsUmrn rename(String name) {
        return new RaceOddsUmrn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceOddsUmrn rename(Name name) {
        return new RaceOddsUmrn(name, null);
    }
}
