/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables;


import crawler.jra.dao.Appdb01;
import crawler.jra.dao.Indexes;
import crawler.jra.dao.Keys;
import crawler.jra.dao.tables.records.RaceOddsFukuRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceOddsFuku extends TableImpl<RaceOddsFukuRecord> {

    private static final long serialVersionUID = 1540448824;

    /**
     * The reference instance of <code>appdb01.race_odds_fuku</code>
     */
    public static final RaceOddsFuku RACE_ODDS_FUKU = new RaceOddsFuku();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceOddsFukuRecord> getRecordType() {
        return RaceOddsFukuRecord.class;
    }

    /**
     * The column <code>appdb01.race_odds_fuku.KAISAI_CD</code>.
     */
    public final TableField<RaceOddsFukuRecord, String> KAISAI_CD = createField("KAISAI_CD", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.RACE_NO</code>.
     */
    public final TableField<RaceOddsFukuRecord, UByte> RACE_NO = createField("RACE_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.ODDS_TIME_NO</code>.
     */
    public final TableField<RaceOddsFukuRecord, UByte> ODDS_TIME_NO = createField("ODDS_TIME_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.UMA_NO</code>.
     */
    public final TableField<RaceOddsFukuRecord, UByte> UMA_NO = createField("UMA_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.NINKI_NO</code>.
     */
    public final TableField<RaceOddsFukuRecord, UByte> NINKI_NO = createField("NINKI_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.FUKU_ODDS_MIN</code>.
     */
    public final TableField<RaceOddsFukuRecord, BigDecimal> FUKU_ODDS_MIN = createField("FUKU_ODDS_MIN", org.jooq.impl.SQLDataType.DECIMAL(6, 1).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.FUKU_ODDS_MAX</code>.
     */
    public final TableField<RaceOddsFukuRecord, BigDecimal> FUKU_ODDS_MAX = createField("FUKU_ODDS_MAX", org.jooq.impl.SQLDataType.DECIMAL(6, 1).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.INSERT_DTTM</code>.
     */
    public final TableField<RaceOddsFukuRecord, Timestamp> INSERT_DTTM = createField("INSERT_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>appdb01.race_odds_fuku.UPDATE_DTTM</code>.
     */
    public final TableField<RaceOddsFukuRecord, Timestamp> UPDATE_DTTM = createField("UPDATE_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>appdb01.race_odds_fuku</code> table reference
     */
    public RaceOddsFuku() {
        this(DSL.name("race_odds_fuku"), null);
    }

    /**
     * Create an aliased <code>appdb01.race_odds_fuku</code> table reference
     */
    public RaceOddsFuku(String alias) {
        this(DSL.name(alias), RACE_ODDS_FUKU);
    }

    /**
     * Create an aliased <code>appdb01.race_odds_fuku</code> table reference
     */
    public RaceOddsFuku(Name alias) {
        this(alias, RACE_ODDS_FUKU);
    }

    private RaceOddsFuku(Name alias, Table<RaceOddsFukuRecord> aliased) {
        this(alias, aliased, null);
    }

    private RaceOddsFuku(Name alias, Table<RaceOddsFukuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RaceOddsFuku(Table<O> child, ForeignKey<O, RaceOddsFukuRecord> key) {
        super(child, key, RACE_ODDS_FUKU);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Appdb01.APPDB01;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RACE_ODDS_FUKU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RaceOddsFukuRecord> getPrimaryKey() {
        return Keys.KEY_RACE_ODDS_FUKU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RaceOddsFukuRecord>> getKeys() {
        return Arrays.<UniqueKey<RaceOddsFukuRecord>>asList(Keys.KEY_RACE_ODDS_FUKU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RaceOddsFukuRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RaceOddsFukuRecord, ?>>asList(Keys.RACE_ODDS_FUKU_IBFK_1);
    }

    public RaceOdds raceOdds() {
        return new RaceOdds(this, Keys.RACE_ODDS_FUKU_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsFuku as(String alias) {
        return new RaceOddsFuku(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsFuku as(Name alias) {
        return new RaceOddsFuku(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceOddsFuku rename(String name) {
        return new RaceOddsFuku(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceOddsFuku rename(Name name) {
        return new RaceOddsFuku(name, null);
    }
}
