/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables;


import crawler.jra.dao.Ihq2xbiptmm0mjtp;
import crawler.jra.dao.Indexes;
import crawler.jra.dao.Keys;
import crawler.jra.dao.tables.records.RaceUmaListRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceUmaList extends TableImpl<RaceUmaListRecord> {

    private static final long serialVersionUID = -1513340850;

    /**
     * The reference instance of <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST</code>
     */
    public static final RaceUmaList RACE_UMA_LIST = new RaceUmaList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceUmaListRecord> getRecordType() {
        return RaceUmaListRecord.class;
    }

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.KAISAI_CD</code>.
     */
    public final TableField<RaceUmaListRecord, String> KAISAI_CD = createField("KAISAI_CD", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.RACE_NO</code>.
     */
    public final TableField<RaceUmaListRecord, UByte> RACE_NO = createField("RACE_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UMA_NO</code>.
     */
    public final TableField<RaceUmaListRecord, UByte> UMA_NO = createField("UMA_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.WAKU_NO</code>.
     */
    public final TableField<RaceUmaListRecord, UByte> WAKU_NO = createField("WAKU_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UMA_NM</code>.
     */
    public final TableField<RaceUmaListRecord, String> UMA_NM = createField("UMA_NM", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.JOCKEY_NM</code>.
     */
    public final TableField<RaceUmaListRecord, String> JOCKEY_NM = createField("JOCKEY_NM", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.INSERT_DTTM</code>.
     */
    public final TableField<RaceUmaListRecord, Timestamp> INSERT_DTTM = createField("INSERT_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UPDATE_DTTM</code>.
     */
    public final TableField<RaceUmaListRecord, Timestamp> UPDATE_DTTM = createField("UPDATE_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST</code> table reference
     */
    public RaceUmaList() {
        this(DSL.name("RACE_UMA_LIST"), null);
    }

    /**
     * Create an aliased <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST</code> table reference
     */
    public RaceUmaList(String alias) {
        this(DSL.name(alias), RACE_UMA_LIST);
    }

    /**
     * Create an aliased <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST</code> table reference
     */
    public RaceUmaList(Name alias) {
        this(alias, RACE_UMA_LIST);
    }

    private RaceUmaList(Name alias, Table<RaceUmaListRecord> aliased) {
        this(alias, aliased, null);
    }

    private RaceUmaList(Name alias, Table<RaceUmaListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RaceUmaList(Table<O> child, ForeignKey<O, RaceUmaListRecord> key) {
        super(child, key, RACE_UMA_LIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ihq2xbiptmm0mjtp.IHQ2XBIPTMM0MJTP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RACE_UMA_LIST_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RaceUmaListRecord> getPrimaryKey() {
        return Keys.KEY_RACE_UMA_LIST_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RaceUmaListRecord>> getKeys() {
        return Arrays.<UniqueKey<RaceUmaListRecord>>asList(Keys.KEY_RACE_UMA_LIST_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RaceUmaListRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RaceUmaListRecord, ?>>asList(Keys.RACE_UMA_LIST_IBFK_1);
    }

    public Race race() {
        return new Race(this, Keys.RACE_UMA_LIST_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaList as(String alias) {
        return new RaceUmaList(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaList as(Name alias) {
        return new RaceUmaList(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceUmaList rename(String name) {
        return new RaceUmaList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceUmaList rename(Name name) {
        return new RaceUmaList(name, null);
    }
}
