/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables;


import crawler.jra.dao.Ihq2xbiptmm0mjtp;
import crawler.jra.dao.Indexes;
import crawler.jra.dao.Keys;
import crawler.jra.dao.tables.records.RaceUmaMarkRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceUmaMark extends TableImpl<RaceUmaMarkRecord> {

    private static final long serialVersionUID = 1298874205;

    /**
     * The reference instance of <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK</code>
     */
    public static final RaceUmaMark RACE_UMA_MARK = new RaceUmaMark();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceUmaMarkRecord> getRecordType() {
        return RaceUmaMarkRecord.class;
    }

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.KAISAI_CD</code>.
     */
    public final TableField<RaceUmaMarkRecord, String> KAISAI_CD = createField("KAISAI_CD", org.jooq.impl.SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.RACE_NO</code>.
     */
    public final TableField<RaceUmaMarkRecord, UByte> RACE_NO = createField("RACE_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.UMA_NO</code>.
     */
    public final TableField<RaceUmaMarkRecord, UByte> UMA_NO = createField("UMA_NO", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.MARK_CD</code>.
     */
    public final TableField<RaceUmaMarkRecord, String> MARK_CD = createField("MARK_CD", org.jooq.impl.SQLDataType.CHAR(2), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.INSERT_DTTM</code>.
     */
    public final TableField<RaceUmaMarkRecord, Timestamp> INSERT_DTTM = createField("INSERT_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.UPDATE_DTTM</code>.
     */
    public final TableField<RaceUmaMarkRecord, Timestamp> UPDATE_DTTM = createField("UPDATE_DTTM", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK</code> table reference
     */
    public RaceUmaMark() {
        this(DSL.name("RACE_UMA_MARK"), null);
    }

    /**
     * Create an aliased <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK</code> table reference
     */
    public RaceUmaMark(String alias) {
        this(DSL.name(alias), RACE_UMA_MARK);
    }

    /**
     * Create an aliased <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK</code> table reference
     */
    public RaceUmaMark(Name alias) {
        this(alias, RACE_UMA_MARK);
    }

    private RaceUmaMark(Name alias, Table<RaceUmaMarkRecord> aliased) {
        this(alias, aliased, null);
    }

    private RaceUmaMark(Name alias, Table<RaceUmaMarkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RaceUmaMark(Table<O> child, ForeignKey<O, RaceUmaMarkRecord> key) {
        super(child, key, RACE_UMA_MARK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ihq2xbiptmm0mjtp.IHQ2XBIPTMM0MJTP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RACE_UMA_MARK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RaceUmaMarkRecord> getPrimaryKey() {
        return Keys.KEY_RACE_UMA_MARK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RaceUmaMarkRecord>> getKeys() {
        return Arrays.<UniqueKey<RaceUmaMarkRecord>>asList(Keys.KEY_RACE_UMA_MARK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RaceUmaMarkRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RaceUmaMarkRecord, ?>>asList(Keys.RACE_UMA_MARK_IBFK_1);
    }

    public RaceUmaList raceUmaList() {
        return new RaceUmaList(this, Keys.RACE_UMA_MARK_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMark as(String alias) {
        return new RaceUmaMark(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMark as(Name alias) {
        return new RaceUmaMark(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceUmaMark rename(String name) {
        return new RaceUmaMark(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceUmaMark rename(Name name) {
        return new RaceUmaMark(name, null);
    }
}
