/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables.records;


import crawler.jra.dao.tables.Kaisai;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KaisaiRecord extends UpdatableRecordImpl<KaisaiRecord> implements Record5<String, String, Date, Timestamp, Timestamp> {

    private static final long serialVersionUID = -7795640;

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.KAISAI.KAISAI_CD</code>.
     */
    public void setKaisaiCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.KAISAI.KAISAI_CD</code>.
     */
    public String getKaisaiCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.KAISAI.KAISAI_NM</code>.
     */
    public void setKaisaiNm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.KAISAI.KAISAI_NM</code>.
     */
    public String getKaisaiNm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.KAISAI.KAISAI_DT</code>.
     */
    public void setKaisaiDt(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.KAISAI.KAISAI_DT</code>.
     */
    public Date getKaisaiDt() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.KAISAI.INSERT_DTTM</code>.
     */
    public void setInsertDttm(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.KAISAI.INSERT_DTTM</code>.
     */
    public Timestamp getInsertDttm() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.KAISAI.UPDATE_DTTM</code>.
     */
    public void setUpdateDttm(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.KAISAI.UPDATE_DTTM</code>.
     */
    public Timestamp getUpdateDttm() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Date, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Date, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Kaisai.KAISAI.KAISAI_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Kaisai.KAISAI.KAISAI_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Kaisai.KAISAI.KAISAI_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Kaisai.KAISAI.INSERT_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Kaisai.KAISAI.UPDATE_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKaisaiNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getKaisaiDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKaisaiNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getKaisaiDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KaisaiRecord value1(String value) {
        setKaisaiCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KaisaiRecord value2(String value) {
        setKaisaiNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KaisaiRecord value3(Date value) {
        setKaisaiDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KaisaiRecord value4(Timestamp value) {
        setInsertDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KaisaiRecord value5(Timestamp value) {
        setUpdateDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KaisaiRecord values(String value1, String value2, Date value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KaisaiRecord
     */
    public KaisaiRecord() {
        super(Kaisai.KAISAI);
    }

    /**
     * Create a detached, initialised KaisaiRecord
     */
    public KaisaiRecord(String kaisaiCd, String kaisaiNm, Date kaisaiDt, Timestamp insertDttm, Timestamp updateDttm) {
        super(Kaisai.KAISAI);

        set(0, kaisaiCd);
        set(1, kaisaiNm);
        set(2, kaisaiDt);
        set(3, insertDttm);
        set(4, updateDttm);
    }
}
