/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables.records;


import crawler.jra.dao.tables.RaceUmaList;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceUmaListRecord extends UpdatableRecordImpl<RaceUmaListRecord> implements Record8<String, UByte, UByte, UByte, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -801285323;

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.KAISAI_CD</code>.
     */
    public void setKaisaiCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.KAISAI_CD</code>.
     */
    public String getKaisaiCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.RACE_NO</code>.
     */
    public void setRaceNo(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.RACE_NO</code>.
     */
    public UByte getRaceNo() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UMA_NO</code>.
     */
    public void setUmaNo(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UMA_NO</code>.
     */
    public UByte getUmaNo() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.WAKU_NO</code>.
     */
    public void setWakuNo(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.WAKU_NO</code>.
     */
    public UByte getWakuNo() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UMA_NM</code>.
     */
    public void setUmaNm(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UMA_NM</code>.
     */
    public String getUmaNm() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.JOCKEY_NM</code>.
     */
    public void setJockeyNm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.JOCKEY_NM</code>.
     */
    public String getJockeyNm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.INSERT_DTTM</code>.
     */
    public void setInsertDttm(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.INSERT_DTTM</code>.
     */
    public Timestamp getInsertDttm() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UPDATE_DTTM</code>.
     */
    public void setUpdateDttm(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST.UPDATE_DTTM</code>.
     */
    public Timestamp getUpdateDttm() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, UByte, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, UByte, UByte, UByte, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, UByte, UByte, UByte, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RaceUmaList.RACE_UMA_LIST.KAISAI_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return RaceUmaList.RACE_UMA_LIST.RACE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return RaceUmaList.RACE_UMA_LIST.UMA_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return RaceUmaList.RACE_UMA_LIST.WAKU_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RaceUmaList.RACE_UMA_LIST.UMA_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return RaceUmaList.RACE_UMA_LIST.JOCKEY_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RaceUmaList.RACE_UMA_LIST.INSERT_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return RaceUmaList.RACE_UMA_LIST.UPDATE_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getUmaNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getWakuNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUmaNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getJockeyNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getUmaNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getWakuNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUmaNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getJockeyNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value1(String value) {
        setKaisaiCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value2(UByte value) {
        setRaceNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value3(UByte value) {
        setUmaNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value4(UByte value) {
        setWakuNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value5(String value) {
        setUmaNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value6(String value) {
        setJockeyNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value7(Timestamp value) {
        setInsertDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord value8(Timestamp value) {
        setUpdateDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaListRecord values(String value1, UByte value2, UByte value3, UByte value4, String value5, String value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceUmaListRecord
     */
    public RaceUmaListRecord() {
        super(RaceUmaList.RACE_UMA_LIST);
    }

    /**
     * Create a detached, initialised RaceUmaListRecord
     */
    public RaceUmaListRecord(String kaisaiCd, UByte raceNo, UByte umaNo, UByte wakuNo, String umaNm, String jockeyNm, Timestamp insertDttm, Timestamp updateDttm) {
        super(RaceUmaList.RACE_UMA_LIST);

        set(0, kaisaiCd);
        set(1, raceNo);
        set(2, umaNo);
        set(3, wakuNo);
        set(4, umaNm);
        set(5, jockeyNm);
        set(6, insertDttm);
        set(7, updateDttm);
    }
}
