/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables.records;


import crawler.jra.dao.tables.RaceOdds;

import java.sql.Time;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceOddsRecord extends UpdatableRecordImpl<RaceOddsRecord> implements Record7<String, UByte, UByte, Time, Time, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1163517761;

    /**
     * Setter for <code>appdb01.race_odds.KAISAI_CD</code>.
     */
    public void setKaisaiCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.KAISAI_CD</code>.
     */
    public String getKaisaiCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>appdb01.race_odds.RACE_NO</code>.
     */
    public void setRaceNo(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.RACE_NO</code>.
     */
    public UByte getRaceNo() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>appdb01.race_odds.ODDS_TIME_NO</code>.
     */
    public void setOddsTimeNo(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.ODDS_TIME_NO</code>.
     */
    public UByte getOddsTimeNo() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>appdb01.race_odds.TNPK_ODDS_TIME</code>.
     */
    public void setTnpkOddsTime(Time value) {
        set(3, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.TNPK_ODDS_TIME</code>.
     */
    public Time getTnpkOddsTime() {
        return (Time) get(3);
    }

    /**
     * Setter for <code>appdb01.race_odds.UMRN_ODDS_TIME</code>.
     */
    public void setUmrnOddsTime(Time value) {
        set(4, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.UMRN_ODDS_TIME</code>.
     */
    public Time getUmrnOddsTime() {
        return (Time) get(4);
    }

    /**
     * Setter for <code>appdb01.race_odds.INSERT_DTTM</code>.
     */
    public void setInsertDttm(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.INSERT_DTTM</code>.
     */
    public Timestamp getInsertDttm() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>appdb01.race_odds.UPDATE_DTTM</code>.
     */
    public void setUpdateDttm(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>appdb01.race_odds.UPDATE_DTTM</code>.
     */
    public Timestamp getUpdateDttm() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, UByte, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, UByte, UByte, Time, Time, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, UByte, UByte, Time, Time, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RaceOdds.RACE_ODDS.KAISAI_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return RaceOdds.RACE_ODDS.RACE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return RaceOdds.RACE_ODDS.ODDS_TIME_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field4() {
        return RaceOdds.RACE_ODDS.TNPK_ODDS_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field5() {
        return RaceOdds.RACE_ODDS.UMRN_ODDS_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return RaceOdds.RACE_ODDS.INSERT_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RaceOdds.RACE_ODDS.UPDATE_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getOddsTimeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component4() {
        return getTnpkOddsTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component5() {
        return getUmrnOddsTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getOddsTimeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value4() {
        return getTnpkOddsTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value5() {
        return getUmrnOddsTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value1(String value) {
        setKaisaiCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value2(UByte value) {
        setRaceNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value3(UByte value) {
        setOddsTimeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value4(Time value) {
        setTnpkOddsTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value5(Time value) {
        setUmrnOddsTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value6(Timestamp value) {
        setInsertDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord value7(Timestamp value) {
        setUpdateDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsRecord values(String value1, UByte value2, UByte value3, Time value4, Time value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceOddsRecord
     */
    public RaceOddsRecord() {
        super(RaceOdds.RACE_ODDS);
    }

    /**
     * Create a detached, initialised RaceOddsRecord
     */
    public RaceOddsRecord(String kaisaiCd, UByte raceNo, UByte oddsTimeNo, Time tnpkOddsTime, Time umrnOddsTime, Timestamp insertDttm, Timestamp updateDttm) {
        super(RaceOdds.RACE_ODDS);

        set(0, kaisaiCd);
        set(1, raceNo);
        set(2, oddsTimeNo);
        set(3, tnpkOddsTime);
        set(4, umrnOddsTime);
        set(5, insertDttm);
        set(6, updateDttm);
    }
}
