/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables.records;


import crawler.jra.dao.tables.RaceOddsTan;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceOddsTanRecord extends UpdatableRecordImpl<RaceOddsTanRecord> implements Record8<String, UByte, UByte, UByte, UByte, BigDecimal, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1197021605;

    /**
     * Setter for <code>appdb01.race_odds_tan.KAISAI_CD</code>.
     */
    public void setKaisaiCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.KAISAI_CD</code>.
     */
    public String getKaisaiCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.RACE_NO</code>.
     */
    public void setRaceNo(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.RACE_NO</code>.
     */
    public UByte getRaceNo() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.ODDS_TIME_NO</code>.
     */
    public void setOddsTimeNo(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.ODDS_TIME_NO</code>.
     */
    public UByte getOddsTimeNo() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.UMA_NO</code>.
     */
    public void setUmaNo(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.UMA_NO</code>.
     */
    public UByte getUmaNo() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.NINKI_NO</code>.
     */
    public void setNinkiNo(UByte value) {
        set(4, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.NINKI_NO</code>.
     */
    public UByte getNinkiNo() {
        return (UByte) get(4);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.TAN_ODDS</code>.
     */
    public void setTanOdds(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.TAN_ODDS</code>.
     */
    public BigDecimal getTanOdds() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.INSERT_DTTM</code>.
     */
    public void setInsertDttm(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.INSERT_DTTM</code>.
     */
    public Timestamp getInsertDttm() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>appdb01.race_odds_tan.UPDATE_DTTM</code>.
     */
    public void setUpdateDttm(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>appdb01.race_odds_tan.UPDATE_DTTM</code>.
     */
    public Timestamp getUpdateDttm() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record4<String, UByte, UByte, UByte> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, UByte, UByte, UByte, UByte, BigDecimal, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, UByte, UByte, UByte, UByte, BigDecimal, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RaceOddsTan.RACE_ODDS_TAN.KAISAI_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return RaceOddsTan.RACE_ODDS_TAN.RACE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return RaceOddsTan.RACE_ODDS_TAN.ODDS_TIME_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return RaceOddsTan.RACE_ODDS_TAN.UMA_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field5() {
        return RaceOddsTan.RACE_ODDS_TAN.NINKI_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return RaceOddsTan.RACE_ODDS_TAN.TAN_ODDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RaceOddsTan.RACE_ODDS_TAN.INSERT_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return RaceOddsTan.RACE_ODDS_TAN.UPDATE_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getOddsTimeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getUmaNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component5() {
        return getNinkiNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getTanOdds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getOddsTimeNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getUmaNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value5() {
        return getNinkiNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getTanOdds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value1(String value) {
        setKaisaiCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value2(UByte value) {
        setRaceNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value3(UByte value) {
        setOddsTimeNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value4(UByte value) {
        setUmaNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value5(UByte value) {
        setNinkiNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value6(BigDecimal value) {
        setTanOdds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value7(Timestamp value) {
        setInsertDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord value8(Timestamp value) {
        setUpdateDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceOddsTanRecord values(String value1, UByte value2, UByte value3, UByte value4, UByte value5, BigDecimal value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceOddsTanRecord
     */
    public RaceOddsTanRecord() {
        super(RaceOddsTan.RACE_ODDS_TAN);
    }

    /**
     * Create a detached, initialised RaceOddsTanRecord
     */
    public RaceOddsTanRecord(String kaisaiCd, UByte raceNo, UByte oddsTimeNo, UByte umaNo, UByte ninkiNo, BigDecimal tanOdds, Timestamp insertDttm, Timestamp updateDttm) {
        super(RaceOddsTan.RACE_ODDS_TAN);

        set(0, kaisaiCd);
        set(1, raceNo);
        set(2, oddsTimeNo);
        set(3, umaNo);
        set(4, ninkiNo);
        set(5, tanOdds);
        set(6, insertDttm);
        set(7, updateDttm);
    }
}
