/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao.tables.records;


import crawler.jra.dao.tables.RaceUmaMark;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RaceUmaMarkRecord extends UpdatableRecordImpl<RaceUmaMarkRecord> implements Record6<String, UByte, UByte, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 248641207;

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.KAISAI_CD</code>.
     */
    public void setKaisaiCd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.KAISAI_CD</code>.
     */
    public String getKaisaiCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.RACE_NO</code>.
     */
    public void setRaceNo(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.RACE_NO</code>.
     */
    public UByte getRaceNo() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.UMA_NO</code>.
     */
    public void setUmaNo(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.UMA_NO</code>.
     */
    public UByte getUmaNo() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.MARK_CD</code>.
     */
    public void setMarkCd(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.MARK_CD</code>.
     */
    public String getMarkCd() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.INSERT_DTTM</code>.
     */
    public void setInsertDttm(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.INSERT_DTTM</code>.
     */
    public Timestamp getInsertDttm() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.UPDATE_DTTM</code>.
     */
    public void setUpdateDttm(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK.UPDATE_DTTM</code>.
     */
    public Timestamp getUpdateDttm() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, UByte, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, UByte, UByte, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, UByte, UByte, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RaceUmaMark.RACE_UMA_MARK.KAISAI_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return RaceUmaMark.RACE_UMA_MARK.RACE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return RaceUmaMark.RACE_UMA_MARK.UMA_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RaceUmaMark.RACE_UMA_MARK.MARK_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return RaceUmaMark.RACE_UMA_MARK.INSERT_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return RaceUmaMark.RACE_UMA_MARK.UPDATE_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getUmaNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMarkCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKaisaiCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getRaceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getUmaNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMarkCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getInsertDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord value1(String value) {
        setKaisaiCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord value2(UByte value) {
        setRaceNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord value3(UByte value) {
        setUmaNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord value4(String value) {
        setMarkCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord value5(Timestamp value) {
        setInsertDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord value6(Timestamp value) {
        setUpdateDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RaceUmaMarkRecord values(String value1, UByte value2, UByte value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceUmaMarkRecord
     */
    public RaceUmaMarkRecord() {
        super(RaceUmaMark.RACE_UMA_MARK);
    }

    /**
     * Create a detached, initialised RaceUmaMarkRecord
     */
    public RaceUmaMarkRecord(String kaisaiCd, UByte raceNo, UByte umaNo, String markCd, Timestamp insertDttm, Timestamp updateDttm) {
        super(RaceUmaMark.RACE_UMA_MARK);

        set(0, kaisaiCd);
        set(1, raceNo);
        set(2, umaNo);
        set(3, markCd);
        set(4, insertDttm);
        set(5, updateDttm);
    }
}
