/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao;


import crawler.jra.dao.tables.Kaisai;
import crawler.jra.dao.tables.Race;
import crawler.jra.dao.tables.RaceOdds;
import crawler.jra.dao.tables.RaceOddsFuku;
import crawler.jra.dao.tables.RaceOddsTan;
import crawler.jra.dao.tables.RaceOddsUmrn;
import crawler.jra.dao.tables.RaceUmaList;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in appdb01
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>appdb01.kaisai</code>.
     */
    public static final Kaisai KAISAI = crawler.jra.dao.tables.Kaisai.KAISAI;

    /**
     * The table <code>appdb01.race</code>.
     */
    public static final Race RACE = crawler.jra.dao.tables.Race.RACE;

    /**
     * The table <code>appdb01.race_odds</code>.
     */
    public static final RaceOdds RACE_ODDS = crawler.jra.dao.tables.RaceOdds.RACE_ODDS;

    /**
     * The table <code>appdb01.race_odds_fuku</code>.
     */
    public static final RaceOddsFuku RACE_ODDS_FUKU = crawler.jra.dao.tables.RaceOddsFuku.RACE_ODDS_FUKU;

    /**
     * The table <code>appdb01.race_odds_tan</code>.
     */
    public static final RaceOddsTan RACE_ODDS_TAN = crawler.jra.dao.tables.RaceOddsTan.RACE_ODDS_TAN;

    /**
     * The table <code>appdb01.race_odds_umrn</code>.
     */
    public static final RaceOddsUmrn RACE_ODDS_UMRN = crawler.jra.dao.tables.RaceOddsUmrn.RACE_ODDS_UMRN;

    /**
     * The table <code>appdb01.race_uma_list</code>.
     */
    public static final RaceUmaList RACE_UMA_LIST = crawler.jra.dao.tables.RaceUmaList.RACE_UMA_LIST;
}
