/*
 * This file is generated by jOOQ.
 */
package crawler.jra.dao;


import crawler.jra.dao.tables.Kaisai;
import crawler.jra.dao.tables.Race;
import crawler.jra.dao.tables.RaceOdds;
import crawler.jra.dao.tables.RaceOddsFuku;
import crawler.jra.dao.tables.RaceOddsTan;
import crawler.jra.dao.tables.RaceOddsUmrn;
import crawler.jra.dao.tables.RaceUmaList;
import crawler.jra.dao.tables.RaceUmaMark;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ihq2xbiptmm0mjtp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ihq2xbiptmm0mjtp.KAISAI</code>.
     */
    public static final Kaisai KAISAI = crawler.jra.dao.tables.Kaisai.KAISAI;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE</code>.
     */
    public static final Race RACE = crawler.jra.dao.tables.Race.RACE;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE_ODDS</code>.
     */
    public static final RaceOdds RACE_ODDS = crawler.jra.dao.tables.RaceOdds.RACE_ODDS;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE_ODDS_FUKU</code>.
     */
    public static final RaceOddsFuku RACE_ODDS_FUKU = crawler.jra.dao.tables.RaceOddsFuku.RACE_ODDS_FUKU;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE_ODDS_TAN</code>.
     */
    public static final RaceOddsTan RACE_ODDS_TAN = crawler.jra.dao.tables.RaceOddsTan.RACE_ODDS_TAN;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE_ODDS_UMRN</code>.
     */
    public static final RaceOddsUmrn RACE_ODDS_UMRN = crawler.jra.dao.tables.RaceOddsUmrn.RACE_ODDS_UMRN;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE_UMA_LIST</code>.
     */
    public static final RaceUmaList RACE_UMA_LIST = crawler.jra.dao.tables.RaceUmaList.RACE_UMA_LIST;

    /**
     * The table <code>ihq2xbiptmm0mjtp.RACE_UMA_MARK</code>.
     */
    public static final RaceUmaMark RACE_UMA_MARK = crawler.jra.dao.tables.RaceUmaMark.RACE_UMA_MARK;
}
