create table if not exists KAISAI (
	KAISAI_CD		CHAR(10)		NOT NULL,
	KAISAI_NM		VARCHAR(32)		NOT NULL,
	KAISAI_DT		DATE			NOT NULL,
	INSERT_DTTM		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD)
);


create table if not exists RACE (
	KAISAI_CD		CHAR(10)			NOT NULL,
	RACE_NO			TINYINT UNSIGNED	NOT NULL,
	INSERT_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD, RACE_NO),
	FOREIGN KEY (KAISAI_CD) REFERENCES KAISAI(KAISAI_CD)
);


create table if not exists RACE_UMA_LIST (
	KAISAI_CD		CHAR(10)			NOT NULL,
	RACE_NO			TINYINT UNSIGNED	NOT NULL,
	UMA_NO			TINYINT UNSIGNED	NOT NULL,
	WAKU_NO			TINYINT UNSIGNED	NOT NULL,
	UMA_NM			VARCHAR(64)			NOT NULL,
	JOCKEY_NM		VARCHAR(64)			NOT NULL,
	INSERT_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD, RACE_NO, UMA_NO),
	FOREIGN KEY (KAISAI_CD, RACE_NO) REFERENCES RACE(KAISAI_CD, RACE_NO)
);


create table if not exists RACE_ODDS (
	KAISAI_CD		CHAR(10)			NOT NULL,
	RACE_NO			TINYINT UNSIGNED	NOT NULL,
	ODDS_TIME_NO	TINYINT UNSIGNED	NOT NULL,
	TNPK_ODDS_TIME	TIME,
	UMRN_ODDS_TIME	TIME,
	INSERT_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO),
	FOREIGN KEY (KAISAI_CD, RACE_NO) REFERENCES RACE(KAISAI_CD, RACE_NO)
);


create table if not exists RACE_ODDS_TAN (
	KAISAI_CD		CHAR(10)			NOT NULL,
	RACE_NO			TINYINT UNSIGNED	NOT NULL,
	ODDS_TIME_NO	TINYINT UNSIGNED	NOT NULL,
	UMA_NO			TINYINT UNSIGNED	NOT NULL,
	NINKI_NO		TINYINT UNSIGNED,
	SORT_NO			TINYINT UNSIGNED,
	TAN_ODDS		DECIMAL(6, 1),
	INSERT_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO, UMA_NO),
	FOREIGN KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO) REFERENCES RACE_ODDS(KAISAI_CD, RACE_NO, ODDS_TIME_NO)
);

create table if not exists RACE_ODDS_FUKU (
	KAISAI_CD		CHAR(10)			NOT NULL,
	RACE_NO			TINYINT UNSIGNED	NOT NULL,
	ODDS_TIME_NO	TINYINT UNSIGNED	NOT NULL,
	UMA_NO			TINYINT UNSIGNED	NOT NULL,
	NINKI_NO		TINYINT UNSIGNED,
	SORT_NO			TINYINT UNSIGNED,
	FUKU_ODDS_MIN	DECIMAL(6, 1),
	FUKU_ODDS_MAX	DECIMAL(6, 1),
	INSERT_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP			NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO, UMA_NO),
	FOREIGN KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO) REFERENCES RACE_ODDS(KAISAI_CD, RACE_NO, ODDS_TIME_NO)
);

create table if not exists RACE_ODDS_UMRN (
	KAISAI_CD		CHAR(10)			NOT NULL,
	RACE_NO			TINYINT UNSIGNED	NOT NULL,
	ODDS_TIME_NO	TINYINT UNSIGNED	NOT NULL,
	UMA_NO_1		TINYINT UNSIGNED	NOT NULL,
	race_odds_fukuUMA_NO_2		TINYINT UNSIGNED	NOT NULL,
	NINKI_NO		TINYINT UNSIGNED,
	SORT_NO			TINYINT UNSIGNED,
	UMRN_ODDS		DECIMAL(6, 1),
	DIFF_RT			DECIMAL(4,2),
	INSERT_DTTM		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DTTM		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO, UMA_NO_1, UMA_NO_2),
	FOREIGN KEY (KAISAI_CD, RACE_NO, ODDS_TIME_NO) REFERENCES RACE_ODDS(KAISAI_CD, RACE_NO, ODDS_TIME_NO)
);

